### ISSUE TITLE
Config Suggestion

### ISSUE THREAD

**Issue by mmmilord** [Abstrusle/PracticalBarrels#2]
First off I want to say very cool client side mod, I ran into some pet peeves trying to use it

If possible, could you add a config for the following opt-in choices that have to be enabled manually?

1. have to be sneaking while right clicking to use the mods quick deposit feature
2. ignore the first-item deposit interaction when a tool is in the mainhand, many times I opened an empty barrel with my sword without wanting to put it in

Thank you for ur time

**Comment by Abstrusle** [comment]
The mod's first step occurs when the barrel screen is opened, rather than a barrel being clicked; Additionally, the requirement of sneaking would prevent placing blocks onto the barrel, which can be excruciating in certain situations. 
As for 2, can probably do a check if the held item is damageable, and override it if said item is already in the barrel. This would be enabled by default (still an option), as barrels of swords and shovels aren't particularly common. An additional setting would be available for if an item doesn't stack. I hope these additional settings will at least mitigate the first issue.

**Comment by mmmilord** [comment]
Hey, thanks for the response. Maybe I'm overreaching here, but instead of the sneak right, what about a modifier + right click? Like shift or ctrl for example (I usually use shift for sprint) so it would not be tied to sneak at all, or for others that would be ctrl instead (default keybinds).

It's just that sometimes, I want to open the barel's inventory regularly without putting the item in my hand immediately, (in the case I am just checking the inv) that means unless there's an item already in it, I always have to change to an empty hand before opening any empty barrel or end up having to reopen the inventory just to pull the item back out. The modifier would control whether or not I want the function to go off.

If this is something too time consuming to implement, or doesn't fit the vision of your mod then no problem thanks for reading.
